In [31]:
import pandas as pd

combat = pd.read_csv('combats.csv')
pokemon = pd.read_csv('pokemon.csv')

In [32]:
import numpy as np

pokemon = pokemon.rename(index=str, columns={"#": "Number"})
numberOfWins = combat.groupby('Winner').count()
countByFirst = combat.groupby('Second_pokemon').count()
countBySecond = combat.groupby('First_pokemon').count()
numberOfWins = numberOfWins.sort_index()
numberOfWins['Total Fights'] = countByFirst.Winner + countBySecond.Winner
numberOfWins['Win Percentage']= numberOfWins.First_pokemon/numberOfWins['Total Fights']
results = pd.merge(pokemon, numberOfWins, left_on='Number', right_index = True, how='left')
results[results['Win Percentage'].isnull()]
results = results.drop(['First_pokemon', 'Second_pokemon', 'Total Fights'], axis=1)
results[np.isfinite(results['Win Percentage'])]
results['Total'] = results['HP'] + results['Attack'] + results['Defense'] + results['Sp. Atk'] + results['Sp. Def'] + results['Speed']
results.insert(10, 'Total', results.pop('Total'))
results.head()

,Number,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Total,Generation,Legendary,Win Percentage
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,318,1,False,0.278195
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,405,1,False,0.380165
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,525,1,False,0.674242
3,4,Mega Venusaur,Grass,Poison,80,100,123,122,120,80,625,1,False,0.560000
4,5,Charmander,Fire,NaN,39,52,43,60,50,65,309,1,False,0.491071

In [33]:
results.to_csv('pokemon_data.csv')